// Generated by CoffeeScript 1.4.0
(function() {
  var airplay, browser;

  airplay = require('airplay');

  browser = airplay.createBrowser();

  browser.on('deviceOnline', function(device) {
    console.log("Device Online: [" + device.id + "]");
    return console.log(device.info_);
  });

  browser.start();

}).call(this);
