// Generated by CoffeeScript 1.4.0
(function() {
  var bcs, bcs1, crypto, first, hmac, key, params, timestamp, url, value, videoId;

  crypto = require('crypto');

  url = "";

  videoId = 489300;

  timestamp = String(Math.round(new Date().getTime() / 1000));

  params = {
    video_id: videoId,
    v: 888324234,
    ts: timestamp,
    np: 1,
    vp: 1,
    pp: 'Desktop',
    dp_id: 'Hulu',
    region: 'US',
    language: 'en'
  };

  bcs1 = "";

  url += "https://s.hulu.com/select?";

  first = 1;

  for (key in params) {
    value = params[key];
    console.log("" + key + ": " + value);
    bcs1 += key + value;
    if (first === 1) {
      url += "" + key + "=" + value;
      first = 0;
    } else {
      url += "&" + key + "=" + value;
    }
  }

  console.log("bcs1: " + bcs1);

  console.log("url: " + url);

  hmac = crypto.createHmac('md5', "f6daaa397d51f568dd068709b0ce8e93293e078f7dfc3b40dd8c32d36d2b3ce1");

  hmac.update(bcs1);

  bcs = hmac.digest('hex');

  url += "&bcs=" + bcs;

  console.log(url);

}).call(this);
