// Generated by CoffeeScript 1.4.0

/* Handle integration with Hulu API
*/


(function() {
  var Hulu;

  exports.Hulu = Hulu = (function() {

    function Hulu(cfg) {
      this.cfg = cfg;
    }

    Hulu.prototype.getShow = function(showId) {
      return console.log(showId);
    };

    return Hulu;

  })();

}).call(this);
