// Generated by CoffeeScript 1.4.0
(function() {
  var Hulu, request;

  request = require('request');

  /* Handle integration with Hulu API
  */


  exports.Hulu = Hulu = (function() {

    function Hulu(cfg) {
      this.cfg = cfg;
      this.url_base = "http://www.hulu.com/api/2.0/videos.json?video_type[]=episodes";
    }

    Hulu.prototype.getShows = function(callback) {
      var id, limit, name, order, shows, sort, url;
      shows = {
        "Parks and Recreation": 1968
      };
      url = this.url_base;
      sort = "original_premiere_date";
      order = "DESC";
      limit = 5;
      for (name in shows) {
        id = shows[name];
        url += "&show_id[]=" + id;
      }
      url += "&sort=" + sort + "&order=" + order + "&items_per_page=" + limit;
      return request(url, function(err, response, body) {
        if (!err && response.statusCode === 200) {
          return callback(JSON.parse(response.body));
        } else {
          return callback(err);
        }
      });
    };

    return Hulu;

  })();

}).call(this);
