// Generated by CoffeeScript 1.6.3
(function() {
  var Hulu, request;

  request = require('request');

  /* Handle integration with Hulu API*/


  exports.Hulu = Hulu = (function() {
    function Hulu(cfg) {
      this.cfg = cfg;
      this.url_base = "http://www.hulu.com/api/2.0/videos.json?video_type[]=episodes";
    }

    return Hulu;

  })();

}).call(this);
