// Generated by CoffeeScript 1.4.0
(function() {
  var Hulu, request;

  request = require('request');

  /* Handle integration with Hulu API
  */


  exports.Hulu = Hulu = (function() {

    function Hulu(cfg) {
      this.cfg = cfg;
      this.url_base = "http://www.hulu.com/api/2.0/videos.json?video_type[]=episodes";
    }

    Hulu.prototype.getShow = function(show, callback) {
      var limit, order, sort, url;
      url = this.url_base;
      sort = "original_premiere_date";
      order = "DESC";
      limit = 5;
      url += "&show_id[]=" + show;
      url += "&sort=" + sort + "&order=" + order + "&items_per_page=" + limit;
      return callback(url);
    };

    return Hulu;

  })();

}).call(this);
