// Generated by CoffeeScript 1.4.0
(function() {
  var TCPConnection, Xbmc, xbmc, _ref;

  _ref = require('xbmc'), TCPConnection = _ref.TCPConnection, xbmc = _ref.xbmc;

  /* Handle integration with XBMC on Apple TV
  */


  exports.Xbmc = Xbmc = (function() {

    function Xbmc(cfg) {
      this.cfg = cfg;
      this.connection = new TCPConnection({
        host: '192.168.1.112',
        port: 8080,
        verbose: true
      });
      this.xbmc = new xbmc;
      this.xbmc.setConnection(this.connection);
      this.xbmc.on('connection:open', function() {
        console.log('Connection!');
        return this.xbmc.message('test!');
      });
    }

    Xbmc.prototype.getAddons = function(result) {
      /* request 'Addons.GetAddons', [], (err, error, response) ->
        console.log 'got here'
        if err
          console.log err
        else
          console.log response
          callback response
      */

    };

    return Xbmc;

  })();

}).call(this);
