// Generated by CoffeeScript 1.6.3
(function() {
  var TCPConnection, Xbmc, XbmcApi, _ref;

  _ref = require('xbmc'), TCPConnection = _ref.TCPConnection, XbmcApi = _ref.XbmcApi;

  /* Handle integration with XBMC on Apple TV*/


  exports.Xbmc = Xbmc = (function() {
    function Xbmc(cfg) {
      var _this = this;
      this.cfg = cfg;
      this.connection = new TCPConnection({
        host: '192.168.1.112',
        port: 8080,
        verbose: true
      });
      this.xbmcApi = new XbmcApi({
        silent: true,
        connection: this.connection
      });
      this.xbmcApi.on('connection:open', function() {
        console.log('Connection!');
        return _this.xbmcApi.message('test!');
      });
      this.xbmcApi.on('connection:error', function() {
        return console.log('error!');
      });
    }

    Xbmc.prototype.getAddons = function(result) {
      return console.log('blah');
      /* request 'Addons.GetAddons', [], (err, error, response) ->
        console.log 'got here'
        if err
          console.log err
        else
          console.log response
          callback response
      */

    };

    return Xbmc;

  })();

}).call(this);
